### ISSUE TITLE
Modify the app.yaml with suitable configs to specify CSRF and XSS ignore URIs

### ISSUE THREAD

**Issue by msmshariq** [wso2/carbon-uuf-maven-tools#53]
In app.yaml file, change the following configs  

```
csrfPatterns:
    accept: []
    reject: []
xssPatterns:
    accept: []
    reject: []
```
to 
```
csrfIgnoreUris: []
xssIgnoreUris: []
```

This is because and app developer only needs to specify the set of URI's that doesn't need CSRF and XSS  protection.
