### ISSUE TITLE
Configuration changes to app.yaml for pluggable authenticator in UUF

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-uuf-maven-tools#66]
Implement the ability to specify a custom authenticator using the app.yaml.

With this implementation, a web developer will be able to specify the authenticator implementation and the logout URI in the `app.yaml` configuration.

An example app.yaml would be as shown below:

```yaml
...
# Authenticator for this app
authenticator: "org.wso2.carbon.uuf.sample.simpleauth.bundle.api.auth.FormParamAuthenticator"

#URI of the logout page in this app.
logoutPageUri: "/simple-auth/logout"
...
```
