### ISSUE TITLE
Introduce app.yaml config changes for session management factory

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-uuf-maven-tools#68]
Previously, the ability to specify a custom session manager using the app.yaml was introduced in #63. However, since it is required to have a session manager per each UUF application instead of having a single global session manager (since it would be easy for the web developer to implement a session manager and since it easily avoids exposing sessions of an UUF app to another UUF app).

Therefore, it is required to implement the ability to specify a custom session manager factory using the app.yaml

An example app.yaml would be as shown below:

```yaml
# Session manager configuration for this app
sessionManagement:
  factoryClassName: "org.wso2.carbon.uuf.api.auth.InMemorySessionManagerFactory"
  timeout: 600
```
