### ISSUE TITLE
Add session management and authorizer configurations to UUF app maven archetype

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-uuf-maven-tools#72]
https://github.com/wso2/carbon-uuf-maven-tools/issues/68 and https://github.com/wso2/carbon-uuf-maven-tools/issues/70 introduced session management and authorizer configurations. However, a new user should be aware of these configurations. Therefore default values of these configurations should be included in the `app.yaml` configuration when the user generates an UUF app with the uuf-application-archetype.

The changed section of the 'app.yaml' configuration should be:

```yaml
...

# Session manager configuration for this app
sessionManagement:
  factoryClassName: "org.wso2.carbon.uuf.api.auth.InMemorySessionManagerFactory"
  timeout: 600

# Authorizer for this app
authorizer: null

...
```
